name = "my-ed-node"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
# 专属认证密钥
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"

# 🚀 使用你自己的新加坡独立原生 VPS 当私享 PROXYIP 出口（100% 解锁 Twitter/YouTube）
PROXYIP = "43.156.148.165:9443"

# 🌏 亚太极速优选 CNAME 域名池
ADD = "saas.sin.fan,cf.090227.xyz,cf.hw.090227.xyz,cf.0sm.com"

# 代理超时与容灾配置
PROXY_TIMEOUT = 1500
PROXY_FALLBACK = "true"
